### ISSUE TITLE
AllowDuplicates won't work when simpleValue is false

### ISSUE THREAD

**Issue by eberridge** [jakezatecky/react-dual-listbox#103]
**Describe the bug**
I need the ability to have the same source option(s) added multiple times to the selected list. This works for simpleValue scenarios. However, I need to use an array of options instead _(reason: after an option is added to the selected list, the user can double click on it, which opens a drawer in which they can edit certain properties, so I need the selected items returned in onChange to include these edits. Duplicates are based on the same original option, but may have differences)_. So those values must be stored in the selected object itself; thus the simple array of values won't work.
When setting simpleValue to false, I do indeed get the object in my onChange callback. But when I try to add it again, onChange continues to get just the one copy of the object.

**Reproduction steps**
**Here is a very simple demo of this**: https://codesandbox.io/s/react-dual-listbox-example-hvr7f
Click on "Option One" to try to add it again. It won't work.
Note that if you comment out line 33 (simpleValue={false}), you are able to add a duplicate.
Original demo used optgroups because that's my scenario. But optgroup use is not necessary to see this. Here's a simpler demo that doesn't use them: https://codesandbox.io/s/react-dual-listbox-example-hvr7f

**Expected behavior**
Able to add the same value multiple times

**Screenshots**
n/a, the demo should suffice

**Comment by jakezatecky** [comment]
Thank you for the demo!
