### ISSUE TITLE
arrow buttons not showing up

### ISSUE THREAD

**Issue by KidProtext** [jakezatecky/react-dual-listbox#107]
![image](https://user-images.githubusercontent.com/57716979/78186045-09d37680-743a-11ea-980c-b6fc05d0e194.png)

Using the simple style sheet react-dual-lisbox.css. It is a simple react app. Not sure what I'm missing. Tried other stylesheets suggested, but none works. I'm a beginner. Appreciate any help.

**Comment by jakezatecky** [comment]
Hello, it looks like the Font Awesome icons cannot load, and this library uses them for those buttons.

Have you ensured that Font Awesome is loaded in the browser? If you have access to the HTML, you can simply add this tag in the `<head>`:

``` html
<link rel="stylesheet" href="//use.fontawesome.com/releases/v5.6.3/css/all.css">
```

**Comment by KidProtext** [comment]
![image](https://user-images.githubusercontent.com/57716979/78456840-265af300-7674-11ea-8a3d-cebbe73755fd.png)

Thank you for the help.

**Comment by jakezatecky** [comment]
Based on the image, it seems like some other style may not be loaded properly (such as `node_modules/react-dual-listbox/lib/react-dual-listbox.css`) or they may be overridden by some CSS on your application (likely using `!important` statements).

I will close this now, but let me know if you have any other problems.

**Comment by KidProtext** [comment]
You are right with the css style. I cleaned it up. However I found another issue. I will log a separate ticket so it doesn't clutter this thread. Thank you.

**Comment by usahai** [comment]
I did a short work-around to get around the fontawesome importing in the browser. I did, however, import the CSS file to get the styling of listbox.
```
import 'react-dual-listbox/lib/react-dual-listbox.css';

<DualListBox
    ...props,
    icons={{
        moveLeft: '<',
        moveAllLeft: '<<',
        moveRight: '>',
        moveAllRight: '>>'
    }}
/>
```

**Comment by winnie-development** [comment]
> Based on the image, it seems like some other style may not be loaded properly (such as `node_modules/react-dual-listbox/lib/react-dual-listbox.css`) or they may be overridden by some CSS on your application (likely using `!important` statements).
> 
> I will close this now, but let me know if you have any other problems.

I had this same issue today and using that tag worked perfectly fine for me.
