### ISSUE TITLE
Hide action buttons

### ISSUE THREAD

**Issue by MishaSavchak** [jakezatecky/react-dual-listbox#108]
Can I hide some action buttons using props. E.g. I want to hide moveAll buttons.
It will be fine to have some flags to config this ones:
hideMoveAllBtns={true}
or some map = [left, right, leftAll, moveAll]
hideButtons={true, false, false, true}

**Comment by jakezatecky** [comment]
You can hide them through CSS (since they have well-defined classes), but I think adding a property for which buttons to render sounds reasonable.

**Comment by MishaSavchak** [comment]
yes I know thanks for the quick response

**Comment by Indrani07** [comment]
Could you please tell me how to hide the action button using css? Also, how can I add text for the button instead of an icon?
