### ISSUE TITLE
Items with same value behave differently with > and >> buttons

### ISSUE THREAD

**Issue by KidProtext** [jakezatecky/react-dual-listbox#112]
**Describe the bug**
Please include a clear and concise description of what the bug is.

**Reproduction steps**
Please include the necessary steps to reproduce the issue as well as a live example that showcases it. You can modify this [CodeSandbox reference point](https://codesandbox.io/s/n37xxln954) to create a working example.

**Expected behavior**
Please include a clear and concise description of what you expected to happen.

**Screenshots**

**Comment by KidProtext** [comment]
Steps to repro:
1. Start with adding two entries to the left list box with two different display names but same value for both entries.
2. Select an item by clicking on it. Both items get selected. That is ok. Now press > button. Both the items are moved into the selected listbox. So far all is well. Move them back to the left listbox.
3. Select an item by clicking on it. Both the items get selected. Now press >> button. Notice the two items are added to the selected lisbox twice. There are a total of 4 entries at this time on the selected listbox. 

The issue seems to be only with >> button handler.

**Comment by KidProtext** [comment]
![dual-arrow-behavior](https://user-images.githubusercontent.com/57716979/83952503-47bc9480-a807-11ea-9752-6c6076f9e365.png)

**Comment by jakezatecky** [comment]
Hello. This component is not really meant to support multiple options with the same value but different names. I am remiss to introduce anything to address this particular issue due to a variety of issues that come into play.

**Comment by jakezatecky** [comment]
Closing due to requirement that each item has a unique value.

A workaround would would be to add a different number at the end of each `value` and once you are ready to save/store the information you can iterate through the `selected` list and remove those numbers.
