### ISSUE TITLE
Reordering with simpleValue={false} does not work

### ISSUE THREAD

**Issue by jschlachtenhaufen** [jakezatecky/react-dual-listbox#113]
**Describe the bug**
Reordering with `simpleValue={false}` does not work, just moves any selected options to the left column

**Reproduction steps**
[See here](https://codesandbox.io/s/react-dual-listbox-example-z7nlm)

**Expected behavior**
I expect the same behavior as when `simpleValue` is true.

**Screenshots**

**Comment by jakezatecky** [comment]
Thanks for the example. I have included this for the next release.

**Comment by AnsurM** [comment]
Hi jakezatecky.
Congratulations for such a brilliant package first of all! Great work.
I just wanted to know is there any update on this ordering issue? 
Thanks.

**Comment by jakezatecky** [comment]
No update, but I hope during this holiday I can devote some time to fixing it.

**Comment by AnsurM** [comment]
I wish you all the best 💪

**Comment by jakezatecky** [comment]
Sorry for the extreme delay, but this has finally landed in v2.1.1.

**Comment by AnsurM** [comment]
This is great to know.

Great job! Keep up the good work buddy. I really appreciate it!
