### ISSUE TITLE
In Firefox, when something is selected from the left menu  the selection area returns to the top of the list.

### ISSUE THREAD

**Issue by serdarsen** [jakezatecky/react-dual-listbox#124]
**Describe the bug**
When something is selected from the left menu, the selection area returns to the top of the list and you have to scroll down the list for each selection over and over again.

**Reproduction steps**
Open [this](https://jakezatecky.github.io/react-dual-listbox/#:~:text=React%20Dual%20Listbox%20is%20a,ready%20to%20try%20it%20out) page in firefox. Scroll a left box to the bottom. Select an item and click right arrow button. The left box will scroll to the top automatically.
https://jakezatecky.github.io/react-dual-listbox/#:~:text=React%20Dual%20Listbox%20is%20a,ready%20to%20try%20it%20out.

**Expected behavior**
Left box shouldn't scroll to the top automatically.

**Screenshots**
![Peek 2020-11-10 14-11](https://user-images.githubusercontent.com/26231317/98667420-6c410d80-235f-11eb-8bdb-66e6c390b65e.gif)

**Comment by jakezatecky** [comment]
Similar, yet different, behavior occurs in Webkit browsers.
