### ISSUE TITLE
Ability to add disabled attribute to specific options

### ISSUE THREAD

**Issue by bodn** [jakezatecky/react-dual-listbox#129]
I have the use case where some options need to be disabled based on a flag in our data. To display to the user that the option is there but cannot be selected based on some condition.

Since react-dual-listbox leverages HTML option tag, is there capacity to add a optional boolean flag to our options data, to set specific options as disabled?

```javascript
const options = [
 { value: 'one', label: 'Option One' },
 { value: 'two', label: 'Option Two' },
 { value: 'three', label: 'Option Three', disabled: true }
]
```

**Comment by jakezatecky** [comment]
This is supported in the v2.1 branch but needs to be released. I'll keep this issue open until then.

**Comment by jakezatecky** [comment]
Covered in #80.
