### ISSUE TITLE
Deselect option from Dual Select box

### ISSUE THREAD

**Issue by souviiik** [jakezatecky/react-dual-listbox#139]
I am using the Basic Example at this link - https://jakezatecky.github.io/react-dual-listbox/.

Now to replicate the issue, you need to add items from left column to right column one by one. You have to move at least 5 elements from left to right. When you move items notice that none of the option stays selected after movement.

Now start moving items from right to left one by one, after some time you will see that item stays highlighted even after moving to left column.

Please help me get this issue resolved. I do not want this highlight to appear.

**Comment by jakezatecky** [comment]
Yeah, this is a weird quirk. I think it has to do with with the React keys. Will take a more detailed investigation to find a solution.
