### ISSUE TITLE
How can i render My own custom list?

### ISSUE THREAD

**Issue by saileshkush95** [jakezatecky/react-dual-listbox#141]
i've data in this format, now how can i render this data .
![Screenshot from 2021-04-11 21-00-48](https://user-images.githubusercontent.com/28560875/114310052-1a1c3800-9b09-11eb-8680-78557b39d207.png)

**Comment by jakezatecky** [comment]
You can map the `name` field to `label` and you should be good to go. For customization rendering of the option component, see #38.
