### ISSUE TITLE
Trying to remove a selected value from a filtered list fails when simpleValue is false and preserveSelectOrder is true

### ISSUE THREAD

**Issue by Holay** [jakezatecky/react-dual-listbox#142]
**Describe the bug**
When simpleValue is false and I try to remove a value from a filtered list, it removed the value in that position for the unfiltered list, meaning trying to remove the first result of a filtered list, actually removes the first result of the unfiltered list

**Reproduction steps**
[CodeSanbox](https://codesandbox.io/s/react-dual-listbox-example-forked-h7ez3?file=/src/components/Widget.js)

- Open the codesandbox link
- See option one and option two selected
- filter the selected list for the string "Two"
- see the result is only "Option Two"
- attempt to remove "Option Two" from the selection
- Option one is removed instead, even though it was not visible at the time

**Expected behavior**
Option two should have been removed from the selection

**Comment by jakezatecky** [comment]
Thanks for the reproduction case.

**Comment by Holay** [comment]
Any updates on this issue?

**Comment by jakezatecky** [comment]
Notable that this failure in behavior also requires `preserveSelectOrder` to be set.
