### ISSUE TITLE
Disable only the multi selection buttons (>> and <<)

### ISSUE THREAD

**Issue by smaaashv2** [jakezatecky/react-dual-listbox#144]
Please include a clear and concise description of the feature or enhancement you would like to have added to the project.
I want to remove the buttons for selecting and deselecting multiple buttons (<< and >>). I tried searching for the props which would enable me to do this, but it looks like there aren't any.
Is there a way to only have single select (>) and single deselect (<) buttons in the dual-listbox component?
Or can we disable only the multiple select/deselect buttons (<< and >>)?

**Comment by sagar-ranglani** [comment]
This would be useful when we do NOT want the user to "De-select" a preselected (and disabled) option.

**Comment by smaaashv2** [comment]
Thank you Jake...
