### ISSUE TITLE
Lodash Security Vulnerabilities

### ISSUE THREAD

**Issue by narayanan79** [jakezatecky/react-dual-listbox#147]
**Describe the bug**
Lodash `v4.17.5` used here is having Security Vulnerabilities.
https://snyk.io/vuln/npm:lodash@4.17.5

**Reproduction steps**
NA

**Expected behavior**
Bump the `lodash` version to latest `4.17.21`

**Screenshots**
![image](https://user-images.githubusercontent.com/2851389/118807831-673cb800-b8c6-11eb-9322-15b25b4b3ce6.png)

**Comment by lordsonvimal** [comment]
Hi. We are blocked in using this package as this vulnerability is present. Please upgrade lodash ASAP

**Comment by logeshpaul** [comment]
I would be great if this is addressed

**Comment by jakezatecky** [comment]
Released via v2.1.2 on npm.

**Comment by logeshpaul** [comment]
Thanks @jakezatecky :)

**Comment by narayanan79** [comment]
Highly appreciate the quick resolution @jakezatecky 
💯
