### ISSUE TITLE
Don't Move disabled items to the other side on clicking >> or <<

### ISSUE THREAD

**Issue by sagar-ranglani** [jakezatecky/react-dual-listbox#148]
In my understanding, disabling items is to restrict users to move those items to that other side. But >> or << options move those items too.

```
>> & << should move only non-disabled items
```

**Comment by jakezatecky** [comment]
Thanks for the report. You are right that this should not be possible when individual items are disabled.

**Comment by DarkGuardsman** [comment]
I'll still seeing this in the latest version. Is a fix being created or is help required?

I have found a temp work around by re-adding the disabled items back to each side after an update.
