### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function on build

### ISSUE THREAD

**Issue by sykes-mirandnf** [jakezatecky/react-dual-listbox#152]
**Describe the bug**
Uncaught TypeError: Super expression must either be null or a function.

**Reproduction steps**
I am currently using create-react-app 17 but after the build I encounter the error. But there is no problem with `yarn start`.

**Expected behavior**
Should be working on build.

**Screenshots**
![image](https://user-images.githubusercontent.com/86846049/125121918-3ab75680-e127-11eb-9058-ad0fa0545d6c.png)

**Comment by joa2341** [comment]
The same thing happens to me.

**Comment by joa2341** [comment]
The same thing happens to me.
![image](https://user-images.githubusercontent.com/74164840/125239225-5424f200-e323-11eb-9f78-1ab333e084a5.png)

**Comment by jakezatecky** [comment]
Are you using the latest version of Webpack? Some people have noted that this appears to be a problem with TerserPlugin that create-react-app uses. I do not use create-react-app personally, but some people have noted that setting `keep_fnames: true` fixes the issue for them. Therefore, setting your webpack.config.js to something like this may solve your issue:

``` js
module.exports = {
  ...

  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: { keep_fnames: true },
      }),
    ],
  },
};
```

**Comment by sykes-mirandnf** [comment]
CRA has built-in webpack, I am not sure yet if I can have custom module.exports fot that.

**Comment by takeruadelbert** [comment]
@sykes-mirandnf @jakezatecky Hi, I encounter the exact same problem. Do you get it work?

**Comment by jakezatecky** [comment]
I do not know what in CRA causes the issue but I recall from back when this issue was opened that I played around with it and got some similar, unusual errors. Unfortunately CRA does a lot of heavy lifting and it is not immediately clear what causes the issue with any code it runs.

**Comment by jakezatecky** [comment]
I just tested with a new app created with `create-react-app` v5.0.1 and `react-dual-listbox` v3.0.1. It does not appear that this issue occurs anymore.
