### ISSUE TITLE
Ability to filter one listbox only

### ISSUE THREAD

**Issue by sclavijo93** [jakezatecky/react-dual-listbox#159]
Ability to filter one listbox only

No filter applied:
![imagen](https://user-images.githubusercontent.com/19956031/136553115-3d3f3310-e13f-4999-aecc-0f24a064d252.png)

Current behavior when filtering:
![imagen](https://user-images.githubusercontent.com/19956031/136562295-dd1d90b5-7a07-4322-9371-b0bf3aee6e20.png)

What I am trying to accomplish:
![imagen](https://user-images.githubusercontent.com/19956031/136552965-522660dc-fbf0-422c-8a11-18ac39e878e3.png)

This is my final product requirement:
<img width="531" alt="imagen" src="https://user-images.githubusercontent.com/19956031/136562377-0f773fd9-a11a-4c29-9d7f-05a8cf4a759c.png">

I've tried the following:
1 - Not passing the prop `canFilter` but a `filterCallback` function with no luck because the `filterCallback` is not being called if `canFilter` is not declared.
2 -  Hiding the inputs via CSS while passing `canFilter` and `filterCallback` to the component. This can fullfill my design requirements but when I type into the custom input the `filterCallback` is being fired and filtering both listbox when I only want to filter the first one.
Examples for the point number 2:

No filter applied:
![imagen](https://user-images.githubusercontent.com/19956031/136565980-559d115f-0498-4218-aa25-fc59ec5daddd.png)

Current behavior when filtering:
![imagen](https://user-images.githubusercontent.com/19956031/136566145-9d2bb50f-8b0e-4c39-a6ae-1f6329b2040c.png)

<details>
<summary>This is my code snippet</summary>

(Is a little bit rudimentary but is just for testing)

```jsx
import React from "react";
import DualListBox from "react-dual-listbox";

const options = [
    {
        label: "Earth",
        options: [{ value: "luna", label: "Moon" }],
    },
    {
        label: "Mars",
        options: [
            { value: "phobos", label: "Phobos" },
            { value: "deimos", label: "Deimos" },
        ],
    },
    {
        label: "Jupiter",
        options: [
            { value: "io", label: "Io" },
            { value: "europa", label: "Europa" },
            { value: "ganymede", label: "Ganymede" },
            { value: "callisto", label: "Callisto" },
        ],
    },
];

class FilterExample extends React.Component {
    state = { filterValue: "", selected: ["luna", "io"] };

    constructor(props) {
        super(props);

        this.onChange = this.onChange.bind(this);
        this.onCustomInputChange = this.onCustomInputChange.bind(this);
    }

    onChange(selected) {
        this.setState({ selected });
    }

    onCustomInputChange(e) {
        this.setState({ filterValue: e.target.value });
    }

    render() {
        const { filterValue, selected } = this.state;

        return (
            <>
                <style>
                    {`input.rdl-filter{
                    display: none
                }`}
                </style>
                My custom input:
                <input
                    value={filterValue}
                    onChange={this.onCustomInputChange}
                    style={{
                        borderRadius: 50,
                        borderColor: "#999999",
                        marginLeft: 10,
                    }}
                />
                <DualListBox
                    canFilter
                    filterCallback={(option) => {
                        if (filterValue === "") {
                            return true;
                        }

                        return new RegExp(filterValue, "i").test(option.label);
                    }}
                    options={options}
                    selected={selected}
                    onChange={this.onChange}
                />
            </>
        );
    }
}
export default FilterExample;

```
</details>

**Comment by jakezatecky** [comment]
This is easily done in userland through some CSS:

``` css
.rdl-selected .rdl-filter-container {
  display: none;
}

/* Apply enough margin to the rightmost control so that it aligns with the left */
.rdl-selected .rdl-control {
  margin-top: 46px;
}
```

This will not affect the results on the rightmost box when filtering with the left box.

I decided against including this as an enhancement. It makes some of the code more unwieldy just to hide one of the filters. It also would either result in yet another filter proper or require overloading the existing `canFilter` to support an array.
