### ISSUE TITLE
Language support for filter input placeholder

### ISSUE THREAD

**Issue by uguremirmustafa** [jakezatecky/react-dual-listbox#166]
Currently there is no easy way to update placeholder text of the search input fields. To be more precise, the input fields when we add `canFilter` prop to the component.

![Screenshot from 2021-11-12 18-13-25](https://user-images.githubusercontent.com/51749393/141489532-473870bb-083c-4399-8cca-9ade34b6c0a6.png)

It would be a great enhancement if we could have a field for `filter input field`s in [this list](https://github.com/jakezatecky/react-dual-listbox/blob/master/src/js/lang/default.js).

**Comment by jakezatecky** [comment]
It is available through `filterPlaceholder` property. This should probably be merged with the `lang` property, but that would necessitate a new major version due to breaking backwards compatibility.

**Comment by uguremirmustafa** [comment]
Oh I didn't see that or didn't expect to find it there. Thank you! This issue can be closed.
