### ISSUE TITLE
On Filter Search in right side box, on select option wrong object is moving.

### ISSUE THREAD

**Issue by TECHIE404** [jakezatecky/react-dual-listbox#189]
**Describe the bug**
On Filter Search in the right side box, on selecting the option based on filter, the first element of the selected list is moving to the left box

**Reproduction steps**
Create a list
Move all objects to the Right side then search for any object by name then try to double click on it. 
On click objects, before the selected object is moving first is deleted from a selected list.

**Expected behavior**
When on click on option after filter result then only those objects should be deleted from a selected list

**Screenshots**
![image](https://user-images.githubusercontent.com/28359609/171568184-3d43e68c-aa6f-4be2-8cc3-8af306ca71c0.png)

**Comment by jakezatecky** [comment]
Cannot reproduce with base properties.

However, if you have both `simpleValues={false}` and `{preserveSelectOrder}`, this does appear to be an issue (#142). Will work on a solution to that issue.

**Comment by TECHIE404** [comment]
ok
