### ISSUE TITLE
Exibição em formato de tabela

### ISSUE THREAD

**Issue by RamiroAlves** [jakezatecky/react-dual-listbox#192]
Algo que seria interessante era a exibição em formato de tabela, algo parecido com a imagem abaixo:

![Captura de Tela 2022-06-08 às 09 54 23](https://user-images.githubusercontent.com/28004679/172621687-38195329-598b-489a-94e2-b9d7dd035c1f.png)

**Comment by jakezatecky** [comment]
This would require a more complex render system or allow user-defined renderers for the selection box. This library makes many assumptions by letting the HTML `<select>` element do the heavy-lifting. Possible, but unlikely to be added.

**Comment by jakezatecky** [comment]
Going to close this as a duplicate of #38, as this would best be done in userland provided that #38 ever landed.
