### ISSUE TITLE
Please update peer dependency to React 18

### ISSUE THREAD

**Issue by cjfreedman** [jakezatecky/react-dual-listbox#196]
We want to update our application to React 18 but cannot because this dual-list-box only supports up to React 17.  Please update to React 18.  Thank you!

**Comment by baranoden** [comment]
Same issue here, this needs to upgrade to 18

**Comment by jakezatecky** [comment]
Added in v2.3.0.

From surface level testing, React 18 appears to works fine. However, due to Enyzme not supporting React 18, the automated tests do not cover it. Replacing Enyzme with React Testing Library is an arduous affair that I don't have the stamina for just yet.
