### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aaronmagi** [jakezatecky/react-dual-listbox#2]
Hey Jake,

I couldn't find your email on github.

I have been using your react-dual-listbox.  I have set it up as a widget component as you had in your example.

The part I'm having trouble wrapping my head around is how do you set the initial selected values?

I can see you used this.state = { selected : ['one']} but I don't believe I should be setting this with a props value?   

```
    this.state = { selected: this.props.selectedListObjects };
```

I wanted to know how to set the initial value for the widget.  I plan to use this component to set various lists of objects.  Different lists will need initial selected states.

Thanks for your awesome react component

Aaron

**Comment by jakezatecky** [comment]
Sorry for the lack of response.

This component is controlled so unfortunately it does not have an equivalent of a `defaultValue` property that can be used in other form elements. The initial selected values would be set using the `selected` property.

If you would like to use the component in a way that is more like `defaultValue`, you could write a small wrapper that effectively manages the state information itself. You could essentially take the `Widget` example and name it something like `UncontrolledDualListBox` and add a property called `defaultValue` and then set the state in the constructor based on this value:

``` jsx
class UncontrolledDualListBox extends React.Component {
    constructor() {
        super();

        this.state = { selected: this.props.defaultValue };
        this.onChange = this.onChange.bind(this);
    }

    onChange(selected) {
        this.setState({ selected });
    }

    render() {
        const { selected } = this.state;

        return <DualListBox selected={selected} {...this.props} />;
    }
}
```

**Comment by aaronmagi** [comment]
Hi @jakezatecky ,

I ended up doing just that :)

I do have another question for you though.  How do I get the value out of the dualListBox once a submit is preformed on the page?  

In my handleSubmit I was not sure how to reference the selected list.

ReactDOM.findDOMNode(this.refs['selectedBox']).value

I do not see a ref being created or maybe I am using it wront and I was not sure how to get the reference to the selected items?

Thank you very much for your support,

Aaron

**Comment by jakezatecky** [comment]
I'll look into adding support for referencing those elements.

**Comment by jakezatecky** [comment]
You can now pass a function to `availableRef` and `selectedRef`. Slated for v0.5.1 release.
