### ISSUE TITLE
`height` on root node no longer changes height of listbox component

### ISSUE THREAD

**Issue by Zajn** [jakezatecky/react-dual-listbox#215]
Hi, I noticed in the most recent release that if the root node is given a `height` attribute through a class, it no longer affects the height of the listbox.

Here are some screenshots from v3.0.1 and v4.0.0 with the addition of a `.tall-listbox` class on the root node of the Basic Example, via the `className` property:

### v3.0.1
<img width="1666" alt="Screen Shot 2022-12-20 at 4 06 47 PM" src="https://user-images.githubusercontent.com/1636886/208766803-e55e0c51-2f47-4c20-9e44-88eeb036e2ba.png">

### v4.0.0
![Screen Shot 2022-12-20 at 4 03 16 PM](https://user-images.githubusercontent.com/1636886/208766833-526e7b8b-6b62-4d8a-9b57-787d0ce32dd3.png)

I think this changed in https://github.com/jakezatecky/react-dual-listbox/commit/ebc2605d3996b2199057a4c539481f2a15856433 with the addition of the `<div class="rdl-controls">` wrapper. 

I found this issue https://github.com/jakezatecky/react-dual-listbox/issues/59 in which adding a height to the root node is the suggested method of managing the height of the component.

Was this intentionally changed, and if so, is there a new recommended way to manage the height of the component?

**Comment by jakezatecky** [comment]
Not intentional. Thanks for identifying this.

You are correct that the addition of the wrapper caused this issue. I will change the CSS for the next release to address this, but you can do the following in a CSS file:

``` css
.rdl-controls {
  height: 100%;
}
```
