### ISSUE TITLE
We lose checked element when rearrange it

### ISSUE THREAD

**Issue by mrudowski** [jakezatecky/react-dual-listbox#217]
**Describe the bug**
before 3.0.1 we could sort elements up and down without loosing the checked element
so we could do it many times (without rechecked element on the list)

Now we have to check it again after every rearrange action 

**Reproduction steps**
here the first version that lost this ability `3.0.1` 
https://codesandbox.io/s/react-dual-listbox-lost-checked-9nqb6b

**Expected behavior**
it would be nice if it could work like before 3.0.1

here a working version `3.0.0`
https://codesandbox.io/s/react-dual-listbox-checked-forked-2g71h6

**Comment by jakezatecky** [comment]
Thanks for the report. This will be available in the next release.

**Comment by mrudowski** [comment]
Thank you!
