### ISSUE TITLE
Is it possible to change header label?

### ISSUE THREAD

**Issue by yujun2017** [jakezatecky/react-dual-listbox#219]
This is a really good library and great to find it. I plan to use it in my project. 
I would like to ask if we can change the header label. Also can we add available total and select total in this library? 

Thanks!

John

**Comment by jakezatecky** [comment]
Yes, you can change the header label by passing the `lang` property. See the [default object](https://github.com/jakezatecky/react-dual-listbox/blob/master/src/js/lang/default.js) for the list of keys/values.

The component does not show the number of total options selected or available. However, it would be easily to calculate that by using `selected.length` for the selected and either `available.length - selected.length` for available total if using defaults, or `available.length` if passing the `allowDuplicates` property.

**Comment by yujun2017** [comment]
Thank you so much!
