### ISSUE TITLE
Order buttons support?

### ISSUE THREAD

**Issue by ArsSirek** [jakezatecky/react-dual-listbox#24]
Hi, thanks for sharing the work, your project seems to be most popular here

Will it be easy to add actions to work with order on selected list, to move up and down selected options? (Something similar to shuttle select from Oracle Apex )

Would you recommend to try to implement that with your project?

Thanks again.

**Comment by jakezatecky** [comment]
This is not currently supported in the component, but you could emulate the behavior by passing the `preserveSelectOrder` property, adding the buttons to the right, and updating the order of `selected`  yourself.

I suppose this is something that could be added to the main component without too much effort. The component already has a bunch of different layout possibilities, and it is not too crazy to imagine this sitting to the right of the selected list. The only issue would be if a user selects multiple items that are not next to each other. Might make sense just to move each item selected up once, even if they are not continuous.

**Comment by mnurik** [comment]
This two methods maybe will be usefull for your component. And you have to put two button near the DualListBox component and call handleMove with true and false values. And for calling DualListBox methods you need set ref prop. In my case "dualListBox"
```
 swap = (index1, index2) => {
    return rightOptions => {
      [rightOptions[index1], rightOptions[index2]] = [rightOptions[index2], rightOptions[index1]];
    };
  }

  handleMove = (isDirectionUpward) => {
    const selected = [...this.refs.dualListbox.getSelectedOptions(this.refs.dualListbox.selected)];
    const rightOptions = [...this.state.selected];

    if (isDirectionUpward) {
      selected.forEach(selectedOption => {
        const index = rightOptions.findIndex(option => selectedOption === option);
        if (index > 0) this.swap(index, index - 1)(rightOptions);
      });
    }
    else {
      selected.reverse().forEach(selectedOption => {
        const index = rightOptions.findIndex(option => selectedOption === option);
        if (index < rightOptions.length - 1) this.swap(index, index + 1)(rightOptions);
      });
    }

    this.setState({ selected: rightOptions });
  }
```

**Comment by chandandas** [comment]
It is working now. The above example of @mnurik helped.

**Comment by chandandas** [comment]
The imp change needs to be done is to specify preserveSelectOrder option in order overwrite default order

**Comment by jakezatecky** [comment]
Thanks for your working code, @mnurik. I ended up taking it and adapting it to this component. There was a minor edge case that needed to be accounted for in the instance where the marked items were all at the highest/lowest position of the selected option. In this instance, the above swap code would end up re-arranging their order if no overall change was necessary but it was easy to account for this.
