### ISSUE TITLE
The filterPlaceholder prop of dualListBox is not passed down to the Filter

### ISSUE THREAD

**Issue by Shiro00000** [jakezatecky/react-dual-listbox#246]
The filterPlaceholder prop of dualListBox is not passed down to the Filter

**Comment by jakezatecky** [comment]
Hello. In release [v4.0](https://github.com/jakezatecky/react-dual-listbox/releases/tag/v4.0.0), the `filterPlaceholder` was merged into the `lang` property. Thus, you should specify the `filterPlaceholder` key in `lang`:

``` js
const lang = {
  filterPlaceholder: 'Some text',
};
```

**Comment by jakezatecky** [comment]
Closing since the comment above should resolve your issue.
