### ISSUE TITLE
Add type="search" to the Filter

### ISSUE THREAD

**Issue by kv3tak** [jakezatecky/react-dual-listbox#247]
Would it be possible to add option to specify the type of the Filter component?

Here is by default the type="text", but I would need to use the type="search" (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search), mainly for the "✖️" icon for clearing the input. 

https://github.com/jakezatecky/react-dual-listbox/blob/master/src/js/components/Filter.jsx#L38

**Comment by jakezatecky** [comment]
Thank you! Changed for the future v6 release.
