### ISSUE TITLE
Filter textbox data not clearing, close and open of popup

### ISSUE THREAD

**Issue by mukkotiram** [jakezatecky/react-dual-listbox#26]
we have a popup and we are using dual list box in popup model, enter some filter values and close popup. Click a button to open popup, filter text box values are not cleared.

how can we set initial state values for this component?

**Comment by jakezatecky** [comment]
That's a reasonable enough ask. There is nothing in the component that allows you to current change the filter search text. I'll see about adding some optional property to control that.

**Comment by jakezatecky** [comment]
You can now pass in `filter` and set the search strings to empty:

``` jsx
<DualListBox filter={{
    available: '',
    selected: '',
}} />
```

This allows you to control the state within the component. Should be paired with `onFilterChange`, but now when you close/re-open the modal, you can update the `filter` property to have empty strings.
