### ISSUE TITLE
Filtering and then moving all options moves all filtered-out options as well

### ISSUE THREAD

**Issue by lmendezr** [jakezatecky/react-dual-listbox#268]
**Describe the bug**
Filtering and then moving "all" items is also moving filtered-out options.

**Reproduction steps**

[CodeSandbox example](https://codesandbox.io/p/sandbox/duallistbox-example-forked-k6mpxx?file=%2Fsrc%2Fcomponents%2FWidget.jsx%3A20%2C22&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsuvpi2w00063b6hv6i25vgn%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsuvpi2w00023b6h4gqz28c4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsuvpi2w00033b6hwofm1nci%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsuvpi2w00053b6hkrjj76di%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsuvpi2w00023b6h4gqz28c4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsuvpi2w00013b6hih9nj3hu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FWidget.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A22%257D%255D%257D%255D%252C%2522id%2522%253A%2522clsuvpi2w00023b6h4gqz28c4%2522%252C%2522activeTabId%2522%253A%2522clsuvpi2w00013b6hih9nj3hu%2522%257D%252C%2522clsuvpi2w00053b6hkrjj76di%2522%253A%257B%2522id%2522%253A%2522clsuvpi2w00053b6hkrjj76di%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsuvpi2w00043b6hf4nfsvh0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsuvpi2w00043b6hf4nfsvh0%2522%257D%252C%2522clsuvpi2w00033b6hwofm1nci%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsuvpi2w00033b6hwofm1nci%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

- Enable `canFilter`
- Filter on any of the sides - available or selected
- Click on move all from the filtered side
- All options (visible and filtered-out options) will move

**Expected behavior**
Only visible options should be moved. 

Note - This works as expected from left-to-right if you move them all back to the "filtered side" and try again without changing the filter. Does not work at all from right-to-left.

**Screenshots**
I grabbed a quick clip showcasing the bug in action:
https://www.loom.com/share/d7e6dab07847452699b59602bc126f63?sid=2831facb-0bd6-4bea-a034-8c30e78269dd

**Comment by jakezatecky** [comment]
Thank you for the the high quality bug report. This is indeed unexpected behavior.

**Comment by lmendezr** [comment]
Thanks @jakezatecky for verifying!

**Comment by jakezatecky** [comment]
Resolved in 9901290309a621b706e3d6ff7cca03579e878cdd and available in version 6,0.3.

**Comment by lmendezr** [comment]
Awesome, I can confirm it now works as expected. Thanks a lot for the speedy fix, @jakezatecky!
