### ISSUE TITLE
Some Icons are not being render: moveLeft, moveAllLeft, moveRight and moveAllRight

### ISSUE THREAD

**Issue by amandabrbz** [jakezatecky/react-dual-listbox#272]
**Describe the bug**
I'm using the v6.0.3 in my project react + typescript, and for some reason, the moveLeft, moveAllLeft, moveRight and moveAllRight icons are not being rendered like moveDown, moveUp, moveTop and moveBottom. 

![Screenshot 2024-03-28 at 12 09 05](https://github.com/jakezatecky/react-dual-listbox/assets/48806439/2b9c2e0a-8982-45fe-be02-720174f96803)

It seems that the object isn't accepting JSX.Elements, and it's rendering the default, which doesn't have the appropriate classes in the export CSS.

![Screenshot 2024-03-28 at 12 07 20](https://github.com/jakezatecky/react-dual-listbox/assets/48806439/a5ef85dd-4b51-4c9b-90e8-9157305f5d36)

![Screenshot 2024-03-28 at 12 12 37](https://github.com/jakezatecky/react-dual-listbox/assets/48806439/8ddd69a8-06be-4c5d-92ad-4e9932cb223b)

```json
"dependencies": {
	"react": "^18.2.0",
	"react-dom": "^18.2.0",
	"react-dual-listbox": "^6.0.3",
	"react-icons": "^4.3.1"
}
```

**Expected behavior**

Show correct icons:

![Screenshot 2024-03-28 at 12 06 52](https://github.com/jakezatecky/react-dual-listbox/assets/48806439/a7371a83-3b8d-4f0c-ad74-908fd84fdc0c)

Here I just downgraded to `"react-dual-listbox": "^5.0.2"`

**Comment by jakezatecky** [comment]
Hello. This is because in v6.0.0 we renamed some of the icons property:

> The keys `moveLeft`, `moveAllLeft`, `moveRight`, and `moveAllRight` are now `moveToAvailable`, `moveAllToAvailable`, `moveToSelected`, and `moveAllToSelected` in all instances. Refer to the table below to rename any affected `icons` or `lang` keys:
>
> | Old Key Name   | New Key Name         |
> | -------------- | -------------------- |
> | `moveLeft`     | `moveToAvailable`    |
> | `moveAllLeft`  | `moveAllToAvailable` |
> | `moveRight`    | `moveToSelected`     |
> | `moveAllRight` | `moveAllToSelected`  |

The name change was because left and right assumes a left-to-right (LTR) configuration. I wanted this component to be more cognizant of right-to-left (RTL) languages.

**Comment by amandabrbz** [comment]
Thanks @jakezatecky for explaining!

In the [documentation](https://github.com/jakezatecky/react-dual-listbox?tab=readme-ov-file#changing-the-default-icons) it's referring to the old way, do you mind if I raise a PR for updating it or what's the best way of doing it?

**Comment by jakezatecky** [comment]
That is an unfortunate oversight. Yes, you may submit a PR to fix this.

**Comment by chiragwootag** [comment]
Please fix this.
