### ISSUE TITLE
onDoubleClick and Arrow buttons do not work in IE 11

### ISSUE THREAD

**Issue by aaronmagi** [jakezatecky/react-dual-listbox#3]
I wanted to know if there is any support for IE 11?

I noticed that both the onDoubleClick and the arrow functions to add a value and back and forth do not work for IE 11.

Is this something that could be fixed, at least the arrow functions?  I get an error:

SCRIPT438: Object doesn't support property or method 'from'

It looks to be happening at 

```
  getSelectedOptions(element) {

    return [...element.options]
        .filter((option) => option.selected)
        .map((option) => option.value);
}
```

I am wondering if it has something to do with the version of babel.

Thank you very much

**Comment by jakezatecky** [comment]
I was unaware that IE11 did not support this (though it does work in IE Edge). If you are using Babel, you can include the Babel polyfill which will add in `Array.from` for IE11.

https://babeljs.io/docs/usage/polyfill/

I should at a note to the README indicating this.

**Comment by aaronmagi** [comment]
Adding polyfill did not fix the issue for IE.  It still is unable to use the arrow functions.

I rewrote getSelectedOptions to work with IE / FF and Chrome as shown below.

I am still unable to get onDoubleClick to work which seems odd since react does render it and IE can use it but it never calls onDoubleClick(event).


Update for IE 11

	getSelectedOptions(element) {
		var element = this.refs[selectRef];
		var selectedOptions = [];
		for (var i=0; i<element.length; i++){
			if (element.options[i].selected) {
				selectedOptions.push(element.options[i].value);
			}
		}
		return selectedOptions;
	}

**Comment by jakezatecky** [comment]
The double-click issue turns out to be a bug with Internet Explorer / MS Edge when registered to `<option>` elements. I filed [an issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10350929/) for MS Edge because this took than I would have liked to find out what was causing that issue.

**Comment by jakezatecky** [comment]
Also verified that adding the polyfill does fix the `Array.from` issues with the button events in IE11.
