### ISSUE TITLE
Options aren't moving from Left ListBox to Right ListBox and vice versa 

### ISSUE THREAD

**Issue by krishnadwarapudi** [jakezatecky/react-dual-listbox#31]
Hey, thanks for sharing the work that you did. The component that you've built is the one that we wanted to use in our project. 

But we are facing an issue when trying out the basic example that you've provided in your docs. When clicking on any of the icons, the console statement prints out correct 'selected' values but the options aren't moving from the list boxes. Just wondering what may be the issue as it's the basic example that we are trying to use. We are using React version-15.5.4. Any input from you regarding this would be of great help for us.

Thanks.

**Comment by jakezatecky** [comment]
If you mean the example code at the beginning of the README, then yeah that will only output to the console. You need to do something like `this.setState({ selected })` and use that state when rendering the component:

``` jsx
const { selected } = this.state;

...

<DualListBox
    options={[
        { value: 'one', label: 'One' },
        { value: 'two', label: 'Two' },
    ]}
    selected={selected}
    onChange={(selected) => {
        this.setState({ selected });
    }}
/>
```

**Comment by krishnadwarapudi** [comment]
Oh, that's where I am doing the mistake. Forgot to update selected and state at the same time. Thanks for pointing that out. 
 I am facing another problem with the font-awesome icons. It's showing up rectangle boxes instead of icons. I've added, 
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.css"> in index.html file to download the font-awesome but still it shows the reactangles. Are there any additional steps that I have to do to get the icons?

**Comment by krishnadwarapudi** [comment]
Hey, actually the rectangle boxes issue is resolved. Apparently it's caused because of font-family:"FontAwesome" is being overridden by another font used in the entire application. So it's not showing up the icons.

**Comment by jakezatecky** [comment]
Glad to hear it.
