### ISSUE TITLE
aligning actions to top in IE 11 display issue

### ISSUE THREAD

**Issue by krteter** [jakezatecky/react-dual-listbox#33]
Using alignActions='top' does not display correctly in IE11 (the buttons display too big for the surrounding container).
![image](https://user-images.githubusercontent.com/22568193/34526154-91f2c292-f06f-11e7-9240-a817a44999b1.png)

**Comment by jakezatecky** [comment]
I can see that in the live example as well. I suspect that is because IE 11 may not play nicely with flexbox, which is extensively used in the library. I will look into if it is easy enough to accommodate IE 11 this weekend.

**Comment by krteter** [comment]
I was able to fix it in my application by setting `flex: 0 1 50%;` on the arrow elements.

**Comment by jakezatecky** [comment]
Feel free to submit and PR and I'll merge the changes.

**Comment by jakezatecky** [comment]
Resolved in #34 .
