### ISSUE TITLE
simpleValue property does not work when optgroups are used as options.

### ISSUE THREAD

**Issue by Navi-nk** [jakezatecky/react-dual-listbox#35]
I am using optgroups for dual list box and when an option is selected I would like to get the label of group that the options belongs. As per docs, when I set simpleValue to false, the selected parameter is always a empty array for any select operation.
It appears simpleValue only works with simple options not with groups of options. Any suggestions on how I can get the group label?

**Comment by jakezatecky** [comment]
@Navi-nk Sorry for the delay. Thanks for reporting this issue.
