### ISSUE TITLE
Default filter can cause "Invalid regular expression" error on user input

### ISSUE THREAD

**Issue by vdh** [jakezatecky/react-dual-listbox#36]
With the current default filter, if someone types in a regex symbol (e.g. "("), it isn't escaped, and can cause an invalid regular expression error: (e.g. `Invalid regular expression: /(/: Unterminated group`)

This happens at [this line in `DualListBox`](https://github.com/jakezatecky/react-dual-listbox/blob/master/src/js/DualListBox.js#L30):
```js
return (new RegExp(filterInput, 'i')).test(option.label);
```

**Comment by jakezatecky** [comment]
Thank you.
