### ISSUE TITLE
type is invalid -- expected a string (for built-in components)

### ISSUE THREAD

**Issue by rodmerritt** [jakezatecky/react-dual-listbox#39]
I'm trying to use the component in a typescript page for SharePoint framework web part and i keep getting this error. Any ideas

React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method

**Comment by jakezatecky** [comment]
Hello @rodmerritt. That could be a number of things. Can you provide a code sample or a link showcasing this error?

**Comment by nystromb** [comment]
@jakezatecky I am also getting this error, but only in my tests. I have created a stackoverflow for the relevant code snippets. This error occurs as soon as I import the DualListBox and render it. 

(see: https://stackoverflow.com/questions/50157694/invariant-violation-when-using-external-component-library)

**Comment by jakezatecky** [comment]
Closing for now. If this issue still persists, please create a (minimal!) live example reproducing this on some sandbox environment (e.g. CodeSandbox, CodePen, JsFiddle).
