### ISSUE TITLE
IE11/Windows 10 - Unable to style option elements or inspect option tags in dev tools

### ISSUE THREAD

**Issue by mallerie** [jakezatecky/react-dual-listbox#40]
This is what the multi select looks like in IE11:
![screen shot 2018-03-07 at 1 59 26 pm](https://user-images.githubusercontent.com/16726365/37112218-cc277332-220f-11e8-8505-033872e24883.png)
And this is what it looks like in Chrome:
![screen shot 2018-03-07 at 1 59 16 pm](https://user-images.githubusercontent.com/16726365/37112220-cc6759ca-220f-11e8-8e11-f212651f05eb.png)
For some reason, it seems that the browser is not recognizing option tags. In all other browsers, the list in the multiselect is rendering correctly. I've tested this issue on multiple machines and the result is always the same(Windows 7 & 10).

Is there any way to change the component to use ul & li elements instead? I have been doing some research online and it looks like IE11 has a ton of bugs related to select and option tags.

**Comment by jakezatecky** [comment]
Hmm...I cannot quite replicate the issue you are facing. I tested the live examples with IE 11 on a Windows 10 machine and did not see the issue in your first screenshot. Can you point to a live example somewhere (e.g. a CodePen, JSFiddle, PasteBin example)?

In relation to using `<ul>` and `<li>` elements: that is certainly possible, but replicating the same styles as the native elements and firing the same events would be a bit annoying. I am not opposed to doing this, but I would need a PR that does most of the work, as it is not a priority for me.

**Comment by mallerie** [comment]
I am working on a fiddle for you now. In the mean time, you can recreate this issue by running a sample of the dual listbox in IE 11 and try to right click on an option in the list to inspect the element. Or try to change the height of the options or make any style changes. You will see that you cannot. This is a known IE11 issue. 

In the meantime, here is an article that explains a problem similar to mine.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5457477/

**Comment by mallerie** [comment]
[https://jakezatecky.github.io/react-dual-listbox/](url)

If you go to your demo in an IE11 browser, and try to inspect one of the options. Notice how even though my mouse is hovered above an option tag, the DOM element highlighting isn't active above that specific element?

![screen shot 2018-03-16 at 1 02 17 pm](https://user-images.githubusercontent.com/16726365/37534276-c49a6c20-291a-11e8-8206-8998f9a4c326.png)

**Comment by jakezatecky** [comment]
As you note, this seems to just be the behavior of IE11. We are afforded certain conveniences when using the native `<select>` elements (namely familiar styles and events) and I am extremely averse to rolling out a set of nodes that mimic their functionality.

Therefore, it looks like this will remain an issue for IE11 and this component as Microsoft has no intentions of making any non-security related updates to that browser. Ideally, IE11 would fully go away (and everyone would be forced to use Edge if they want to use a Microsoft browser) but at least until that day comes the component appears to largely _otherwise_ function properly for IE11.
