### ISSUE TITLE
options are not moving individually, but will move when moving all options

### ISSUE THREAD

**Issue by janelle-boyd** [jakezatecky/react-dual-listbox#41]
Hi, i'm currently facing an issue where if i have a list of unselected options and go to move one option over, it doesn't display on the 'selected' side. However, when I do "move all" it moves it to the other side.

Is there something that I'm missing?

**Comment by janelle-boyd** [comment]
I realized that if one item is selected, I receive back [object Object]. However, i'm not sure what to do with this. I've already tried JSON.parse() it and JSON.stringify().

**Comment by janelle-boyd** [comment]
I figured it out! 😃 I had a nested array for the value, so I had to apply JSON.stringify to my object before passing it through your code. Hope this helps someone else 😄 

Then when I need the original format, I'll either convert it back or maybe even keep an unmodified version of the selected items. Happy coding!!

**Comment by jakezatecky** [comment]
Glad you figured it out.
