### ISSUE TITLE
Suggestion: No selection text

### ISSUE THREAD

**Issue by bunkscene** [jakezatecky/react-dual-listbox#43]
Hi,

I am using your component for an app I am building.  Very nice.  One feature I need is to place text "inside" the selected box when nothing is selected.

I wrote a complicated component that will hide the select box and insert a div holding my text when zero options are selected.

This could be a nice feature to add.

Thanks,
Dave

**Comment by jakezatecky** [comment]
This would not be too hard to add, but I think some of the actions might cause some minor errors of the selection box is missing. It would not be too hard for the component to account for these situations. It would probably also make sense to add the same feature to the available box as well, when all options have been exhausted.

**Comment by jakezatecky** [comment]
Resolved in b77c229e8fe4a6d1cb6296c7ff71a5fa44b4a7c1.
