### ISSUE TITLE
Font Awesome issue

### ISSUE THREAD

**Issue by teaglebuilt** [jakezatecky/react-dual-listbox#44]
I have the dual list functional. Other than your custom css that we import, is there a way we can customize the component? Also I have font awesome installed, yet the icons are not displayed within this controlled component? can you please enlighten me?

**Comment by gaetandeschamps** [comment]
Hi, I don't have the icons displayed on the actions in the middle. Can anyone help ?

**Comment by jakezatecky** [comment]
For the most part, your customization on any aesthetics is limited to changing any CSS rules or CSS variables. There are additional properties you can supply to change the orientation of some of the action buttons, but that is about it as far as non-CSS customization goes.

I just updated the examples to use Font Awesome 5 and the icons seem to render fine. Previously the examples page was pointing to the older Font Awesome 4. See the current examples: https://jakezatecky.github.io/react-dual-listbox/

Can you post a live example where the Font Awesome icons do not render?

**Comment by teaglebuilt** [comment]
I figured it out actually i just had to find out the right version
