### ISSUE TITLE
Selected list is not getting displayed

### ISSUE THREAD

**Issue by priyanka2211** [jakezatecky/react-dual-listbox#45]
Hi,

I'm using this component in one of my feature. I'm facing some issues in rendering selected options.

This is my code snippet

renderElement() {
    let listOptions = = ['test', 'test2'];
    let generalListOptions = [{value: 'list', label: 'list'},{value: 'list1', label: 'list1'}];
    return (
        <DualListBox canFilter
          options={generalListOptions}
          selected={listOptions}
          onChange={(selected) => {this.listChangeHandler(selected)}}
        />
      );
  }

After rendering: (second list box is empty)

![image](https://user-images.githubusercontent.com/4748195/42553565-fa908d6a-84fe-11e8-9399-469102fcedb8.png)

Data in handler: Once I select "list 1".
selected array has ["test", "test2", "list1"]
![image](https://user-images.githubusercontent.com/4748195/42553501-bc30ebc8-84fe-11e8-8b53-06a572bb395f.png)

Can you help me on why selected list is not getting displayed?

**Comment by priyanka2211** [comment]
I have found that elements in selected array by default goes to hidden list

![image](https://user-images.githubusercontent.com/4748195/42556188-6da1d9c2-8508-11e8-94dc-78c351c2df69.png)

But I haven't mentioned any options to get selected list to be hidden

**Comment by jakezatecky** [comment]
It looks like when you initially render you are supplying `test` and `test2` as the initially selected values. However, those items do not appear in the `generalListOptions` variable, which might explain why they are not being rendered. All of the options, whether they are available or selected, should be defined in the `options` parameter. This parameter defines the display names for any options (the "label") as well as any child dependencies, if necessary.

The hidden input merely renders whatever was passed to the `selected` array, whether or not they are in the `options` parameter.

**Comment by priyanka2211** [comment]
Okay. Now I get this.

"Options" is the super set and "Selected" is the subset of options.

I'm maintaining options and selected list in the state of my component.
Options = [1, 2, 3, 4, 5] Selected = []
When user selects "1, 2" options, so I update both the lists as Options = [3, 4, 5] and Selected = [1, 2]. This is why I don't get any values in selected list.

Can you help me how to hide selected options from Options?

**Comment by priyanka2211** [comment]
I got how this is working.

Only issue I found it now is, when I try to add items from options to selected, adding last item to the list makes some of items in selected list to multiply itself.

Like, 
`allOptions = [
      { value: "one", label: "one" },
      { value: "two", label: "two" },
      { value: "three", label: "three" },
      { value: "four", label: "four" }
    ];`
selected = []
Selected array after each movement:
When I try to add "one" =>               ` ["one"]`
then "two" =>                                     `["one", "two"]`
then "three" =>                                   `["one", "one", "two", "four"]` (one repeated twice)
then "four" (last time in options) =>    `["one", "one", "two", "one", "one", "two", "four", "three"]` ("one" repeated 4 times)

Sample code available here: https://codesandbox.io/s/k3rj2x2853

**Comment by priyanka2211** [comment]
Got it working. Thanks for your help!

**Comment by karishma-sweety** [comment]
@priyanka2211 could you please share the solution
Even I am facing the same issue
Selected data is not displaying
