### ISSUE TITLE
Is it possible to move up and down the selected items

### ISSUE THREAD

**Issue by chandandas** [jakezatecky/react-dual-listbox#46]
Hi,

I am using this plugin and really good! However i need to implement an up and down functionality where i should be able to select an item on right side list and move up and down by using buttons.

Is it possible?

regards,
Chandan

**Comment by jakezatecky** [comment]
Hello @chandandas. There is currently no way to do this with the component currently. You can look at #24, where someone else provided some code to emulate this behavior. It may be added in the next feature release, but that does not have a definite date.
