### ISSUE TITLE
Dual Listbox is not taking containers height

### ISSUE THREAD

**Issue by annjawn** [jakezatecky/react-dual-listbox#47]
It seems that currently the dual listbox isn't taking it's container's height and is set to a predefined height. Is there a way to set the height?

**Comment by jakezatecky** [comment]
Container heights are **usually** determined by the child's height, not the other way around. In the case of this component, no height is being specified for the listbox, and it is just "autoing" to whatever the browser sees fit. However, if this component is included in some flex container with the appropriate settings, it _should_ stretch its height to match other children of that container.

Usually, however, you will have to set the height manually, which you could do with the following CSS:

``` css
.rdl-control {
  height: 200px;
}
```

**Comment by annjawn** [comment]
I did a `height: 100%;` instead of fixed `px` value for the list boxes so that it fills in the container's size. By the way, I have tested and the RDL always gets a static height no matter what the container height is without the `height: 100%;`, I think putting `height: 100%;` on `.rdl-listbox` and `.react-dual-listbox` is a good idea. This will make the RDL fill the container's height and also not mess with the controls (left- right arrows) center alignment.

I am using RDL inside of a SUIR Modal and here is what mine looks after I put a Modal height and `height: 100%;` on rdl css.

![image](https://user-images.githubusercontent.com/26977294/45048728-80777a80-b031-11e8-9140-9e08052a7578.png)

**Comment by jakezatecky** [comment]
I am glad that you found an appropriate solution. Hopefully other people who come across a similar issue will find your post helpful as well.

Setting the height to 100% may not work in all cases (in particular, setting both `.react-dual-listbox` and `.rd-listbox` to `height: 100%` causes some alignment issues on the examples page supplied with this project), so I will be passing on implementing that for now unless we can come up with a more generally workable change that largely maintains the current dimensions for the examples page.
