### ISSUE TITLE
Duplicate items in selected

### ISSUE THREAD

**Issue by Neuroforge** [jakezatecky/react-dual-listbox#48]
Hello,

This a great component, thank you!

Is it possible to duplicate options?

i.e. Move an item from options to selected, but it also remains in options. Then you can add the item again.

i.e. In a demo, you could add moon twice.

Regards,

**Comment by jakezatecky** [comment]
No, there is not, but that is a great feature request!

**Comment by jakezatecky** [comment]
Feature implemented in `v1.4-dev` branch. Expecting a release later in the week.

**Comment by chandandas** [comment]
Dear @jakezatecky ,

It would be very  helpful if you release v1.4 over weekend.

Thanks.
