### ISSUE TITLE
in first Basic Examples "move left" moves only part of selected items

### ISSUE THREAD

**Issue by mrudowski** [jakezatecky/react-dual-listbox#58]
step to reproduce:

- Click `Move all right`
- Focus on Selected List and select all items
- Click `Move left`
- Only part of elements were back to left list

**Comment by jakezatecky** [comment]
Thank you so much for finding this so quickly. I cannot believe this slipped by and I have adjusted the tests appropriately so that this should not happen for future releases. Given the severity of this issue, I went ahead a released a new patch version that contains this fix.
