### ISSUE TITLE
Is it possible to load async options?

### ISSUE THREAD

**Issue by oscarlnetoo** [jakezatecky/react-dual-listbox#63]
Hello @jakezatecky,

I am needing to load async options from a remote source as the user types.
Is it possible to do with this component?

**Comment by oscarlnetoo** [comment]
Thank you for the reply!

Yes, I am referring to the filter input.
I know the async component of react-select lib. It's the same idea, but I want a dual list instead of a select.
I would appreciate that feature in your lib.

**Comment by jakezatecky** [comment]
An [example of asynchronous loading of `options`](https://github.com/jakezatecky/react-dual-listbox/blob/v6.0-dev/examples/src/js/LazyFilterExample.jsx) using the `onFilterChange` callback is now present in the `v6.0-dev` branch, and will filter itself into the main branch eventually.
