### ISSUE TITLE
Filtering slow with large datasets

### ISSUE THREAD

**Issue by Zajn** [jakezatecky/react-dual-listbox#75]
Hello, and thanks for the great work on this component! We've noticed that when using larger datasets with the DualListBox component, filtering with the built-in filtering function or a custom filtering function can be very slow. This example is using the built-in filtering, and you should see my keystrokes as they happened in the bottom-right:

![2019-04-30 10 54 58](https://user-images.githubusercontent.com/1636886/56971078-8bd66380-6b36-11e9-9038-ed56483edd88.gif)

There are around 2500 options in this scenario. We're using a slightly more complex filtering function, and tried to debounce the call to that, but weren't able to successfully do so. We also tried to use the `filter` and `onFilterChange` properties to try and debounce the update to the filter input's value. 

Do you have any suggestions or recommendations on what we could in situations where we would like to filter over a large dataset?

**Comment by jakezatecky** [comment]
@Zajn I identified part of the code that was resulting in O(n^2) complexity and have reduced it to O(n). This likely would have adversely affected your large number of options.

Can you try `2.0.0-alpha.0` on npm to see if this improves your performance?

**Comment by Zajn** [comment]
@jakezatecky `2.0.0-alpha.0` _drastically_ improved performance! There is still a slight bit of input lag between a keystroke and seeing it appear in the filter box on the first and second character, but this is a huge improvement.

Thanks so much for the quick response!

**Comment by jakezatecky** [comment]
v2.0.0 released. A future release might also contain additional performance optimizations if there is enough interest. For now, I am closing this issue.

**Comment by bbhagavan** [comment]
Hi @jakezatecky,
Could you please suggest any technique/way for faster filtering of around 23k records using this library.
