### ISSUE TITLE
Swap the Selected and Available options.

### ISSUE THREAD

**Issue by jeloooooo** [jakezatecky/react-dual-listbox#76]
Hi,

Is it possible to swap the location Selected and Available box options? Wherein the Selected options will be on the left, and the Available options will be on the right?

Thanks

**Comment by jakezatecky** [comment]
There is no such option. This would be relatively straightforward to add, however, Am I correct to assume that this is for supporting right-to-left languages?

**Comment by jeloooooo** [comment]
Yes, you are correct. Thanks @jakezatecky

**Comment by jeloooooo** [comment]
thanks man!
