### ISSUE TITLE
All values are selected with single moveLeft key

### ISSUE THREAD

**Issue by alateefah** [jakezatecky/react-dual-listbox#77]
The move left button doesn't seem to be capturing the selected value, irrespective of how many is selected from the right. 

See screenshot below:

![image](https://user-images.githubusercontent.com/9999881/57683160-0f11b200-762b-11e9-9a77-29cb629ac008.png)

**Usage**
 

    class FeatureModule extends Component {

        assignPermissions = (selected) => {
            console.log(selected)
        }

        render () {
                const { features, moduleFeatures } = this.state;
                let featuresList = [], moduleFeaturesList = [];

                if (features.length > 0) {
                    featuresList = features.map(feature => (
                        { value: feature.id, label: feature.name }            
                    ));
                 }

                 if (moduleFeatures.length > 0) {
                     moduleFeatures.map(moduleFeature => (
                         moduleFeaturesList.push(moduleFeature.id)        
                    ));
                  }
                 
                  return (
                             <DualListBox
                                         canFilter
                                         options = {featuresList} 
                                         selected={moduleFeaturesList}                         
                                         onChange={(selected) =>  this.assignPermissions(selected)} 
                                         icons={{
                                                 moveLeft: <Icon name="angle left" />,
                                                 moveAllLeft: [
                                                     <Icon key={0} name="angle double left" />,
                                                 ],
                                                 moveRight: <Icon name="angle right" />,
                                                 moveAllRight: [
                                                     <Icon key={0} name="angle double right" />,
                                                ]
                                          }}  
                                          showNoOptionsText = {true}   
                                          selectedLabel = "Assigned Feature"    
                                          availableLabel = "Available Features"              
                                     />
                   )

        }

**Comment by jakezatecky** [comment]
I cannot replicate this issue with the given code sample. Can you modify this [live example](https://codesandbox.io/s/n37xxln954) to illustrate this issue?

What version are you using? An older version of the library indeed had an issue with the move left button (#58) that was fixed and released. Are you using numeric IDs for values? If so, that is a known issue that has been resolved in the development branch, but not released yet on master and npm (#73).

**Comment by alateefah** [comment]
@jakezatecky yes I am using numeric IDs for value. I guess this ([#73](https://github.com/jakezatecky/react-dual-listbox/issues/73)) solves my problem. Looking forward to its release. Thank you

**Comment by jakezatecky** [comment]
Upgraded `v2.0.0-alpha.0` to `v2.0.0`. Issue should be fixed for latest installs.
