### ISSUE TITLE
Git tags missing for 2.0.0-alpha.0 and 2.0.0

### ISSUE THREAD

**Issue by shepmaster** [jakezatecky/react-dual-listbox#78]
**Describe the bug**

The changelog links to:
https://github.com/jakezatecky/react-dual-listbox/compare/v1.4.2...v2.0.0

**Reproduction steps**

Navigate to https://github.com/jakezatecky/react-dual-listbox/compare/v1.4.2...v2.0.0

**Expected behavior**

I should be able to see the diff between these two versions.

I also would like to be able to do https://github.com/jakezatecky/react-dual-listbox/compare/v2.0.0.alpha.0...v2.0.0

**Comment by jakezatecky** [comment]
Thanks for pointing this out! That was certainly a mistake on my part. I might have to use `np` in the future to avoid this situation again.

Both tags were pushed to the repo, and although v2.0.0.alpha.0 and v2.0.0 have some (minor) differences between them, the GitHub comparison is not showing these differences, even though a `git diff` shows a clear difference between them.

**Comment by shepmaster** [comment]
Thank you!
