### ISSUE TITLE
Need to add 'disabled' props for options for making specific options disabled. like 'react-select'

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [jakezatecky/react-dual-listbox#80]
Please include a clear and concise description of the feature or enhancement you would like to have added to the project.

As we render the list of select option we can make some options disabled as per required. In such case there should be a props with options object which will state either this option is disabled or enabled .

Example is below 
options should be like this

`const options = [
    { value: 'one', label: 'Option One' , disabled: true},
    { value: 'two', label: 'Option Two' , disabled: false},
];`

So option 'one' will be shown but will be disabled in the list.

**Comment by jakezatecky** [comment]
Sorry for the late acknowledgement. This will be shipped in the next release.

**Comment by jakezatecky** [comment]
Nothing set for the moment, but I might do an early v2.1 release and push back the other items to v2.2.
