### ISSUE TITLE
To add an attribute in options tag of react-dual-listbox

### ISSUE THREAD

**Issue by rimpa92** [jakezatecky/react-dual-listbox#87]
I have options which are large in length and I want to add 'title' attribute to it. Could you please suggest how to do so?

**Comment by jakezatecky** [comment]
Sorry for the lack of reply. I have been on quite the hiatus but an moving back to being more active again.

In regards to your question, there is not support for this feature. However, this would be trivial to add and thus warrants inclusion in the next feature release. Thanks for the suggestion.

**Comment by rimpa92** [comment]
You are welcome 🙂. Please try to incorporate the changes in next release.
Would help a lot

**Comment by jakezatecky** [comment]
Feature added to future v2.1 release.
