### ISSUE TITLE
How to update selected list from parent component?

### ISSUE THREAD

**Issue by pranavBD96** [jakezatecky/react-dual-listbox#98]
Hi, 

I have created a modal spawning from a button where a user can input a list of labels. I parse the options array and found all the matches. When I try to push these label value pairs to the selected array it does't work. Here is the line of code I am doing.

this.setState({selected: this.state.selected.push(list)});

**Comment by jakezatecky** [comment]
Hello, it is hard to determine what might be going from the example line of code. Could you post to a live example (such as forking [this live version](https://codesandbox.io/s/n37xxln954) and adding relevant data)?

**Comment by pranavBD96** [comment]
Thanks for the response!

I have forked it and added my index.js and index.css files.

https://5vnrm.csb.app/

https://codesandbox.io/s/react-dual-listbox-example-5vnrm

**Comment by pranavBD96** [comment]
@jakezatecky  Let me know if the code I posted is a bit confusing. I know it isn't too neat and there is a lot of code. I can be clearer if there is any confusion!

Best,
Pranav

**Comment by pranavBD96** [comment]
I realized the selected array only takes the values, not the labels as well. I got it fixed!

**Comment by jakezatecky** [comment]
Sorry for the lack of response. Good to hear that you resolved it.
