### ISSUE TITLE
which font-awesome library should I use for react-redux application

### ISSUE THREAD

**Issue by shubhkush1234** [jakezatecky/react-dual-listbox#99]
Hi, 
Nice work!
It would be great if you'll provide the font-awesome library it'll need as a dependancy, coz there are too many (probably 3 or 4) available for npm. I am still not able to fix the styling of my component. Please guide me what import statement I should use and what npm-package I need to use for the styles.

My component looks like this:

import DualListBox from 'react-dual-listbox';

const options = [
    { value: 'one', label: 'Option One' },
    { value: 'two', label: 'Option Two' },
];

class Counter extends Component {
    state = {
        counter: 0,
        selected: ['one']
    }

    onChange = (selected) => {
        this.setState({ selected });
    };

    render () {
        const { selected } = this.state;

        return (
            <div>
                <CounterOutput value={this.props.ctr} />
                <CounterControl label="Increment" clicked={() => this.counterChangedHandler( 'inc' )} />
                <CounterControl label="Decrement" clicked={() => this.counterChangedHandler( 'dec' )}  />
                <CounterControl label="Add 5" clicked={() => this.counterChangedHandler( 'add', 5 )}  />
                <CounterControl label="Subtract 5" clicked={() => this.counterChangedHandler( 'sub', 5 )}  />
                <div>
                    <DualListBox
                    options={options}
                    selected={selected}
                    onChange={this.onChange}
                />
                </div>
            </div>
        );
    }
}

const mapStateToProps= ( state ) => {
    return {
        ctr: state.counter
    }
}

export default connect(mapStateToProps)(Counter);

**Comment by jakezatecky** [comment]
The main reason I do not define Font Awesome as a dependency is in case if someone wants to load the icons through a separate stylesheet or CDN, as opposed to within a JavaScript import, or wants to use their own icons (through the `icons` property).

The library itself should support Font Awesome 4 or 5 (though not 3 or lower). There are a few options available.

1. You could just import the Font Awesome styles through a CDN and include it in the HTML file, such as in the [example HTML](https://github.com/jakezatecky/react-dual-listbox/blob/master/examples/src/index.html):

``` html
<link rel="stylesheet" href="//use.fontawesome.com/releases/v5.6.3/css/all.css">
```

2. You _should_ be able to use `font-awesome` from NPM and import it through JavaScript (assuming you have an appropriate CSS loader):

``` jsx
import "font-awesome/css/font-awesome.min.css";
```

3. You could create a separate stylesheet and load Font Awesome through there:

`style.css`
``` css
@import url("https://use.fontawesome.com/releases/v5.6.3/css/all.css");
```

`App.js`
``` jsx
import "path/to/style.css";
```
4. Finally, you could also import `react-fontawesome` library and define the icons themselves, modifying the base object:

``` jsx
<DualListBox
    ...
    icons={{
        moveLeft: <FontAwesomeIcon icon="chevron-left" />
        moveAllLeft: ...,
        moveRight: ...,
        moveAllRight: ...,
        moveDown: ...,
        moveUp: ...,
    }}
/>
```

**Comment by shubhkush1234** [comment]
Thanks, it helped!
